Add build support for swfdec 0.7.
And prioritize newer versions over older ones.

diff --git a/src/modules/swfdec/configure b/src/modules/swfdec/configure
--- a/src/modules/swfdec/configure
+++ b/src/modules/swfdec/configure
@@ -2,17 +2,30 @@
 
 if [ "$help" != "1" ]
 then
-	pkg-config swfdec-0.8 2> /dev/null
+	pkg-config swfdec-0.9 2> /dev/null
 	disable_swfdec=$?
-	if [ "$disable_swfdec" != "0" ]
+	if [ "$disable_swfdec" = "0" ]
 	then
-		pkg-config swfdec-0.9 2> /dev/null
+		echo "CFLAGS += $(pkg-config --cflags swfdec-0.9)" >> config.mak
+		echo "LDFLAGS += $(pkg-config --libs swfdec-0.9)" >> config.mak
+	else
+		pkg-config swfdec-0.8 2> /dev/null
 		disable_swfdec=$?
-		if [ "$disable_swfdec" != "0" ]
+		if [ "$disable_swfdec" = "0" ]
 		then
-			echo "- swfdec not found: disabling"
-			touch ../disable-swfdec
-			exit 0
+			echo "CFLAGS += $(pkg-config --cflags swfdec-0.8)" >> config.mak
+			echo "LDFLAGS += $(pkg-config --libs swfdec-0.8)" >> config.mak
+		else
+			pkg-config swfdec-0.7 2> /dev/null
+			disable_swfdec=$?
+			if [ "$disable_swfdec" = "0" ]
+				echo "CFLAGS += $(pkg-config --cflags swfdec-0.7)" >> config.mak
+				echo "LDFLAGS += $(pkg-config --libs swfdec-0.7)" >> config.mak
+			then
+				echo "- swfdec not found: disabling"
+				touch ../disable-swfdec
+				exit 0
+			fi
 		fi
 	fi
 fi
