src/framework/mlt_consumer.c src/framework/mlt_consumer.h + Added a general profile handling for size, aspect ratio and display ratio
src/framework/mlt_producer.c
+ Correction to aspect ratio properties

src/inigo/inigo.c
+ Minimalist support for sdl_preview (still not very good)

src/modules/avformat/consumer_avformat.c
+ Takes consumer profile into account

src/modules/core/filter_resize.c
+ Corrections for synthesised producers and aspect ratio (inherits from consumer)

src/modules/core/producer_colour.c
src/modules/core/producer_noise.c
src/modules/gtk2/producer_pango.c
+ Ensures that resize picks up consumer aspect ratio

src/modules/dv/consumer_libdv.c
+ Honour wide screen output

src/modules/gtk2/producer_pixbuf.c
+ Correction for 1:1 aspect ratio

src/modules/kino/Makefile
src/modules/kino/avi.cc
src/modules/kino/avi.h
src/modules/kino/configure
src/modules/kino/filehandler.cc
+ Attempt to allow mov dv files to provide audio

src/modules/sdl/consumer_sdl.c
src/modules/sdl/consumer_sdl_preview.c
src/modules/sdl/consumer_sdl_still.c
+ Takes consumer profile into account


git-svn-id: https://mlt.svn.sourceforge.net/svnroot/mlt/trunk/mlt@736 d19143bc-622f-0410-bfdd-b5b2a6649095

diff --git a/src/modules/kino/configure b/src/modules/kino/configure
--- a/src/modules/kino/configure
+++ b/src/modules/kino/configure
@@ -6,12 +6,18 @@ then
 	lqt-config --prefix > /dev/null 2>&1
 	lqt_disabled=$?
 
+	pkg-config libdv 2> /dev/null
+	libdv_disabled=$?
+
 	echo > config.h
 	[ "$lqt_disabled" = "0" ] && echo "#define HAVE_LIBQUICKTIME" >> config.h
+	[ "$libdv_disabled" = "0" ] && echo "#define HAVE_LIBDV" >> config.h
 	echo > config.mak
 	[ "$lqt_disabled" = "0" ] && echo "HAVE_LIBQUICKTIME=1" >> config.mak
+	[ "$libdv_disabled" = "0" ] && echo "HAVE_LIBDV=1" >> config.mak
 
 	[ "$lqt_disabled" != "0" ] && echo "- libquicktime not found: only enabling dv avi support"
+	[ "$libdv_disabled" != 0 -a "$lqt_disabled" = "0" ] && echo "- libdv not found: mov dv may not have audio"
 
 	echo "kino			libmltkino$LIBSUF" >> ../producers.dat
 fi
