+ Cleaned up swig build so it doesn't require an mlt++ install first - Temporarily disabled java
git-svn-id: https://mlt.svn.sourceforge.net/svnroot/mlt/trunk/mlt++@784 d19143bc-622f-0410-bfdd-b5b2a6649095

diff --git a/mlt++/swig/configure b/mlt++/swig/configure
--- a/mlt++/swig/configure
+++ b/mlt++/swig/configure
@@ -7,14 +7,14 @@ which mlt-config > /dev/null 2>&1
 [ $? != 0 ] && echo "Please install mlt" && exit 1
 
 if [ "$1" = "all" ]
-then languages="java perl python ruby tcl"
+then languages="perl python ruby tcl"
 elif [ "$1" != "" ]
 then languages=$*
 else echo "Usage: ./configure [ all | language * ]"
 	 exit 0
 fi
 
-for i in java perl python ruby tcl
+for i in perl python ruby tcl
 do
 	rm -f .$i
 done
@@ -22,16 +22,21 @@ done
 for i in $languages
 do
 	echo -n "Configuring $i ... "
-	cd $i
-	output=`./build 2>/dev/null`
-	if [ $? == 0 ]
-	then echo "OK"
-		 touch ../.$i
-	elif [ "$output" == "" ]
+	if [ -d "$i" ] 
 	then
-		echo "Failed"
+		cd $i &&
+		output=`./build 2>/dev/null`
+		if [ $? == 0 ]
+		then echo "OK"
+		 	touch ../.$i
+		elif [ "$output" == "" ]
+		then
+			echo "Failed"
+		else
+			echo $output
+		fi
+		cd ..
 	else
-		echo $output
+		echo "Unknown"
 	fi
-	cd ..
 done
