jackrack/configure: add detection for ladspa and disable if not detected
git-svn-id: https://mlt.svn.sourceforge.net/svnroot/mlt/trunk/mlt@1034 d19143bc-622f-0410-bfdd-b5b2a6649095

diff --git a/src/modules/jackrack/configure b/src/modules/jackrack/configure
--- a/src/modules/jackrack/configure
+++ b/src/modules/jackrack/configure
@@ -9,13 +9,22 @@ then
 	which xml2-config > /dev/null 2>&1
 	disable_xml2=$?
 
-	if [ "$disable_jack" = "0" -a "$disable_xml2" = "0" ]
+	disable_ladspa=1
+	ladspa_prefix=`which listplugins 2> /dev/null`
+	if [ "$ladspa_prefix" != "" ]
+	then
+		ladspa_prefix=`dirname "$ladspa_prefix"`
+		disable_ladspa=`[ -f "$ladspa_prefix/include/ladspa.h" ] && echo 1 || echo 0`
+	fi
+
+	if [ "$disable_jack" = "0" -a "$disable_xml2" = "0" -a "$disable_ladspa" = "0" ]
 	then
 		echo "jackrack		libmltjackrack$LIBSUF" >> ../filters.dat
 		echo "ladspa		libmltjackrack$LIBSUF" >> ../filters.dat
 	else
 		[ "$disable_jack" = "1" ] && echo "- jackrack not found: disabling"
 		[ "$disable_xml2" = "1" ] && echo "- xml2 not found: disabling jackrack"
+		[ "$disable_ladspa" = "1" ] && echo "- ladspa not found; disabling"
 		touch ../disable-jackrack
 	fi
 
