Disable jackrack when unavailable
git-svn-id: https://mlt.svn.sourceforge.net/svnroot/mlt/trunk/mlt@704 d19143bc-622f-0410-bfdd-b5b2a6649095

diff --git a/src/modules/jackrack/configure b/src/modules/jackrack/configure
--- a/src/modules/jackrack/configure
+++ b/src/modules/jackrack/configure
@@ -3,8 +3,19 @@
 if [ "$help" != "1" ]
 then
 
-cat << EOF >> ../filters.dat
-jackrack		libmltjackrack$LIBSUF
-EOF
+	pkg-config jack
+	disable_jack=$?
+
+	which xml2-config > /dev/null 2>&1
+	disable_xml2=$?
+
+	if [ "$disable_jack" == "0" -a "$disable_xml2" == "0" ]
+	then
+		echo "jackrack		libmltjackrack$LIBSUF" >> ../filters.dat
+	else
+		[ "$disable_jack" == "1" ] && echo "- jackrack not found: disabling"
+		[ "$disable_xml2" == "1" ] && echo "- xml2 not found: disabling jackrack"
+		touch ../disable-jackrack
+	fi
 
 fi
