Disable xine when mmx not available
git-svn-id: https://mlt.svn.sourceforge.net/svnroot/mlt/trunk/mlt@698 d19143bc-622f-0410-bfdd-b5b2a6649095

diff --git a/src/modules/xine/configure b/src/modules/xine/configure
--- a/src/modules/xine/configure
+++ b/src/modules/xine/configure
@@ -3,9 +3,16 @@
 if [ "$help" != "1" ]
 then
 
-cat << EOF >> ../filters.dat
-deinterlace		libmltxine$LIBSUF
-EOF
+	# Horrible hack
+	grep mmx /proc/cpuinfo > /dev/null 2>&1
+	disable_xine=$?
 
+	if [ "$disable_xine" == "0" ]
+	then
+		echo "deinterlace		libmltxine$LIBSUF" >> ../filters.dat
+	else
+		echo "- MMX Capabalities not found: disabling xine deinterlacing module"
+		touch ../disable-xine
+	fi
 fi
 
