Disable vorbis when unavailable
git-svn-id: https://mlt.svn.sourceforge.net/svnroot/mlt/trunk/mlt@700 d19143bc-622f-0410-bfdd-b5b2a6649095

diff --git a/src/modules/vorbis/configure b/src/modules/vorbis/configure
--- a/src/modules/vorbis/configure
+++ b/src/modules/vorbis/configure
@@ -3,9 +3,16 @@
 if [ "$help" != "1" ]
 then
 
-cat << EOF >> ../producers.dat
-vorbis		libmltvorbis$LIBSUF
-EOF
+	pkg-config vorbisfile 2> /dev/null
+	disable_vorbis=$?
+
+	if [ "$disable_vorbis" == "0" ]
+	then
+		echo "vorbis		libmltvorbis$LIBSUF" >> ../producers.dat
+	else
+		echo "- ogg vorbis not found - disabling"
+		touch ../disable-vorbis
+	fi
 
 fi
 
