Fix getting python includedir
In ROSA 2016.1 it is /usr/include/python3.5m and build script tried to find /usr/include/python3.5
Use python-config to get includes

diff --git a/src/swig/python/build b/src/swig/python/build
--- a/src/swig/python/build
+++ b/src/swig/python/build
@@ -13,9 +13,8 @@ fi
 if [ $? = 0 ]
 then
 	# Change this as needed
-	export PYTHON_INCLUDE=`"$PYTHON" -c "import sys;print(\"{}/include/python{}.{}\".format(sys.prefix,*sys.version_info))"`
-
-	[ ! -d "$PYTHON_INCLUDE" ] && echo "$PYTHON" development missing && exit 1
+	export PYTHON_INCLUDE="$("${PYTHON}-config" --includes)"
+	[ -z "$PYTHON_INCLUDE" ] && echo "$PYTHON" development missing && exit 1
 
 	ln -sf ../mlt.i
 
