Disable libsamplerate when unavailable
git-svn-id: https://mlt.svn.sourceforge.net/svnroot/mlt/trunk/mlt@702 d19143bc-622f-0410-bfdd-b5b2a6649095

diff --git a/src/modules/resample/configure b/src/modules/resample/configure
--- a/src/modules/resample/configure
+++ b/src/modules/resample/configure
@@ -3,9 +3,16 @@
 if [ "$help" != "1" ]
 then
 
-cat << EOF >> ../filters.dat
-resample		libmltresample$LIBSUF
-EOF
+	pkg-config samplerate 2> /dev/null
+	disable_samplerate=$?
+
+	if [ "$disable_samplerate" == "0" ]
+	then
+		echo "resample		libmltresample$LIBSUF" >> ../filters.dat
+	else
+		echo "- libsamplerate not found: disabling"
+		touch ../disable-resample
+	fi
 
 fi
 
