Disable sox when unavailable
git-svn-id: https://mlt.svn.sourceforge.net/svnroot/mlt/trunk/mlt@705 d19143bc-622f-0410-bfdd-b5b2a6649095

diff --git a/src/modules/sox/configure b/src/modules/sox/configure
--- a/src/modules/sox/configure
+++ b/src/modules/sox/configure
@@ -3,8 +3,15 @@
 if [ "$help" != "1" ]
 then
 
-cat << EOF >> ../filters.dat
-sox		libmltsox$LIBSUF
-EOF
+	which libst-config > /dev/null 2>&1
+	disable_sox=$?
+
+	if [ "$disable_sox" == "0" ]
+	then
+		echo "sox		libmltsox$LIBSUF" >> ../filters.dat
+	else
+		echo "- sox not found: disabling"
+		touch ../disable-sox
+	fi
 
 fi
